# Project information
site_name: Mike's Maya Tools

site_url: https://mike-isaakidis.github.io/Maya-Modelling-Tools/
site_author: Michail Isaakidis
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices


nav:
  - Home: 
    - index.md

  - Tools:
    - Tools Page/index.md
    - Batch Exporter: 
      - Batch Exporter/index.md
      - "How to Install": Batch Exporter/how_to_install.md
      - "Buttons Overview": Batch Exporter/Buttons_overview.md
      - "Breakdown": Batch Exporter/Breakdown.md

    - Baking Manager: 
      - Baking Manager/index.md
      - "How to Install": Baking Manager/How to install.md
      - "Rename Features": 
        - "Rename Vanilla": Baking Manager/Rename Features.md
        - "Rename Tool": Baking Manager/Rename Tool.md
      - "Select Features": Baking Manager/Select Features.md
      - "Ungroup Features": Baking Manager/Ungroup Features.md
      - "Outliner Features": Baking Manager/Outliner Features.md
      - "Wireframe Features": Baking Manager/Wireframe Features.md
      - "Baking Workflow": 
        - Baking Manager/Baking_workflow/index.md
        - "Marmoset Baking": Baking Manager/Marmoset Baking.md
        - "Substance Baking": Baking Manager/Substance Baking.md
      - "Vertex Colours Tool": Baking Manager/Vertex Colours Tool.md
      - "Layers Button Overview": Baking Manager/Layers Button Overview.md
      - "Layers Window": Baking Manager/Layers Window.md
      - "Tips Hotkeys": Baking Manager/Tips Hotkeys.md
    - Batch Material Creation: 
      - Batch Material Creation/index.md
      
  - Free Tools: 
    - Free Tools/index.md
    - Duplicate Faces: Free Tools/Duplicate Faces.md
    - Extract Faces: Free Tools/Extract Faces.md
    - Unreal Collision: Free Tools/Unreal Collision.md
  
  - Create Hotkeys/Shelf Buttons: 
    - Create Hotkeys Shelf Buttons/index.md

  - Changelog:
    - Changelog/index.md

  - Reach out:
    - Reach out/index.md




theme:
  name: material
  #name: readthedocs
  #logo: images/favicon.png

  #icon:
  #  logo: fontawesome/solid/bat-cowboy
  favicon: images/favicon.png

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.selections
    #- navigation.indexes #This feature flag is not compatible with toc.integrate, as sections cannot host the table of contents due to missing space.
    #- navigation.expand
    - navigation.top
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - navigation.indexes #This feature flag is not compatible with toc.integrate, as sections cannot host the table of contents due to missing space.
    #- toc.integrate # will remove table of contents and integrate on the left

  language: en
  palette:

    - scheme: slate
      primary: teal
      accent: deep orange

    # old way where you could switch between night and day mode
    #- scheme: default
    #  toggle:
    #   icon: material/toggle-switch-off-outline 
    #   name: Switch to dark mode
    #  primary: teal
    #  accent: deep orange
    #- scheme: slate
    #  toggle:
    #   icon: material/toggle-switch
    #   name: Switch to light
    #  primary: teal
    #  accent: deep orange

  icon:
    logo: logo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: Table of Contents

plugins:
  - search
  - glightbox

extra:
  generator: false #removed the made with mdocs in the footer of the page
  social:
    - icon: simple/artstation
      link: https://www.artstation.com/michailisaakidis/store?tab=digital_product
      name: Artstation Store

    - icon: simple/gumroad
      link: https://mike3d.gumroad.com/
      name: Gumroad Store

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@michailisaakidis
      name: Youtube Channel


extra_css:
  - css/custom.css

copyright: Copyright &copy; 2025 Michail Isaakidis

