# Project information
site_name: Maya Tool Baking Manager

site_url: https://michail-82.github.io/Maya-Modelling-Tools/
site_author: Michail Isaakidis
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices


nav:
  #- Home: index.md
  - Home: home.md

  #- Home: https://mike-isaakidis.github.io/Maya-Modelling-Tools/home/

  - Tools:
    - Batch Exporter: 
      - "Overview": Batch Exporter/Overview.md
    - Baking Manager: 
      - "Overview": Baking Manager/overview.md
      - "Rename Features": Baking Manager/Rename Features.md
      - "Select by Colour": Baking Manager/Select By Colour.md
      - "Ungroup Features": Baking Manager/Ungroup Features.md
      - "Outliner Features": Baking Manager/Outliner Features.md
      - "Wireframe Features": Baking Manager/Wireframe Features.md
      - "Baking Workflow":
        - "Baking Workflow": Baking Manager/Baking Workflow.md
        - "Marmoset Baking": Baking Manager/Marmoset Baking.md
        - "Substance Baking": Baking Manager/Substance Baking.md
      - "Vertex Colours Tool": Baking Manager/Vertex Colours Tool.md
      - "Layers Button Overview": Baking Manager/Layers Button Overview.md
      - "Layers Window": Baking Manager/Layers Window.md
      - "Tips Hotkeys": Baking Manager/Tips Hotkeys.md
    - Batch Material Creation: 
      - "Overview": Batch Material Creation/Overview.md
      




  - Free Tools: 
    - Duplicate Faces: Free Tools/Duplicate Faces.md
    - Extract Faces: Free Tools/Extract Faces.md
    - Unreal Collision: Free Tools/Unreal Collision.md


  




theme:
  name: material
  #name: readthedocs
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.selections
    #- navigation.indexes #This feature flag is not compatible with toc.integrate, as sections cannot host the table of contents due to missing space.
    #- navigation.expand
    - navigation.top
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    #- toc.integrate # will remove table of contents and integrate on the left


  plugins:
    - search
    - zoom


  language: en
  palette:
    - scheme: default
      toggle:
       icon: material/toggle-switch-off-outline 
       name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
       icon: material/toggle-switch
       name: Switch to light
      primary: teal
      accent: deep orange

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true
      title: Table of Contents


extra_css:
  - css/custom.css


copyright: Copyright &copy; 2026 Michail Isaakidis

extra:
  generator: false #removed the made with mdocs in the footer of the page

extra_javascript:
  - https://cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.min.js
  - js/zoom-init.js